### ISSUE TITLE
Coverage report wanted

### ISSUE THREAD

**Issue by mahnen** [cherenkov-plenoscope/merlict_development_kit#35]
When GCOV is so important, cant we have two builds? One for running the tests and a second one for GCOV with '-O0'?

_Originally posted by @relleums in https://github.com/cherenkov-plenoscope/merlict_development_kit/pull/28_

**Comment by mahnen** [comment]
I think it is OK if the travis build is the "slow" coverage build. At the same time, we could offer the standard fast build for everyone who actually uses merlict.

**Comment by mahnen** [comment]
PR #36 shall deal with it.

**Comment by relleums** [comment]
Maybe I have to accept that test-, and coverage-code is build with '-O0'. I just remembered that I did it myself this way when using [mighty valgrind](http://valgrind.org/). This [discussion](https://stackoverflow.com/questions/36930207/code-coverage-with-optimization) also supports this mind-set.

I think the PR #28 already tried to solve this in the right way. You added an if-else-block.

```
if(USE_GCOV)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -O0 --coverage")
    message(STATUS "The compiler flags ${CMAKE_CXX_FLAGS} are set for coverage reports.")
else()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -march=native")
    message(STATUS "The compiler flags ${CMAKE_CXX_FLAGS} are not set for coverage reports.")
endif()
```
The only thing that bothered me was the use of '-O3' instead of '-O1'. So I changed it locally on my machine.
But the resulting execution-speed was different to when I put the optimization-flag [where it was before](https://github.com/cherenkov-plenoscope/merlict_development_kit/blob/3ca12fe815bdd229170e3c0ff9dfe24979c867ec/CMakeLists.txt#L10).

Execution-time of unit-tests on my Intel 4700QM:

putting the optimization-flag  [where it was before](https://github.com/cherenkov-plenoscope/merlict_development_kit/blob/3ca12fe815bdd229170e3c0ff9dfe24979c867ec/CMakeLists.txt#L10)
- '-O0' 5.4s
- '-O1' 1.5s
- '-O3' 1.5s

putting it in the if-else-block:
- '-O0' 5.4s
- '-O1' 5.4s
- '-O3' 5.4s

Because of this, and because of '-O3' being [considered to be a compatibility issue](https://wiki.gentoo.org/wiki/GCC_optimization), I prefer '-O1'.

**Comment by mahnen** [comment]
#36 is now with -O1, also in the -DUSE_COV branch of the build. Seems to work.
